apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
  - hpa.yaml

configMapGenerator:
- name: my-config
  files:
  - config/config.conf
generatorOptions:
  disableNameSuffixHash: true


 