apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-example
spec:
  selector:
    matchLabels:
      app: java-app
  replicas: 2
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: java-app
          image: >-
            quay.io/redhattraining/hello-world-nginx:latest
          ports:
            - containerPort: 8080
